language: python

python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install codecov
script:
  - pylint --rcfile=.pylintrc-shush bsx3/backend/
  - pytest --cov-report term --cov=bsx3/backend
after_success:
  - codecov