language: python

python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pylint
script:
  - pylint --rcfile=.pylintrc-shush src/backend/
  - pytest src/backend
  - pytest --cov=src/backend