language: python

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install codecov
script:
  - pylint --rcfile=.pylintrc-shush bsx3/backend/
  - pytest --cov-report term --cov=bsx3/backend
after_success:
  - codecov