language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_retry pip install -r requirements_python2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3'* ]]; then travis_retry pip3 install -r requirements_python3.txt; fi
script:
  - python -m pytest
  - pylint -E HardwareObjects/EMBL
#  - pylint -E *py
#  - pylint -E HardwareObjects/*py
#  - pylint -E HardwareObjects/abstract/*py
#  - pylint -E HardwareObjects/mockup/*py

